[server]
host = "localhost"
port = 3000

# [connections.default]
# host = "localhost"
# port = 3143
# auth = "password"
# tls = false
# username = "username"
# password = "password"
# mailbox = "INBOX"

[connections.oauth]
host = "imap.gmail.com"
port = 993
tls = true
auth = "xoauth2"
username = "mhaisham79@gmail.com"
access_token = { secret = "ya29.a0AcM612zWc9UCVxiFnG7jgsN0660Ku9SV_caCuciCWh6WmiNbH8z2TW8xXt2S88Jxwu7EC7VP3ka8vMazyUCMRzvOFx5iJfQL6wQcWlxv1gKJTUanIXbK2QcUJmQJbB_m-WCaeauxYL1w-nz1x1w2q5_lfJKl6MY-VBy6aCgYKAZgSAQ8SFQHGX2MizREiH0nLEcegVv44vfjW0g0171" }
refresh_token = { secret = "1//0gtxV2iR0pgaTCgYIARAAGBASNwF-L9Ircz_ApR0T0xczYLZZLek5AR7FcPkvhPtQWurKzznLJzOp8xv95TYE2LvrindRz2bVLLc" }
mailbox = "INBOX"
flavour = "gmail"

[connections.oauth.config]
client_id = "344694291321-vnq4dju7cktp6g17tr2gjt43s91gv8lg.apps.googleusercontent.com"
client_secret = "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"
token_uri = "https://oauth2.googleapis.com/token"
scope = "https://mail.google.com/"
